server:
  name: Staff Fee Privilege API
  port: 8080
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: username
  password: password

database:
  connectString: localhost/XE
  user: hr
  password: welcome
  poolMin: 3
  poolMax: 30

api:
  name: staff-fee-privilege-api
  endpointUri: https://api.oregonstate.edu/v1
