api:
  name: staff-fee-privilege
  endpointUri: ${ENDPOINTURI}

server:
  basePath: /api/v1
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

database:
  connectString: ${DBURL}
  user: ${DBUSER}
  password: ${DBPASSWD}
  poolMin: 3
  poolMax: 30

logger:
  size: 10m
  path: logs
  pattern: YYYY-MM-DD
  archive: true
  colorize: true
  jsonConsole: true
