api:
  name: staff-fee-privilege
  endpointUri: https://api.oregonstate.edu/v1

server:
  basePath: /api/v1
  port: 8080
  adminPort: 8081
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: username
  password: password

database:
  connectString: localhost/XE
  user: hr
  password: welcome
  poolMin: 3
  poolMax: 30

logger:
  size: 10m
  maxFiles: 5
  path: logs
  pattern: YYYY-MM-DD
  archive: true
  colorize: true
  jsonConsole: true
